---
name: Action

"on":
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  zero_two:
    name: Test action (0.2.0)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # 5.0.1
        with:
          persist-credentials: false

      - name: Generate a configuration file
        run: |
          echo "[[group]]" > labelflair.toml
          echo "colors = { tailwind = 'red' }" >> labelflair.toml
          echo "labels = ['bug']" >> labelflair.toml

      - name: Sync labels
        uses: ./
        with:
          config-file: labelflair.toml
          dry-run: true
          version: "0.2.0"
